#!/bin/bash
# Insecure setup: mimics a sloppy sysadmin leaving credentials around

# ── Users ────────────────────────────────────────────────────────────────────

# guest: low-privilege read-only user
if ! id guest &>/dev/null; then
    useradd -m -s /bin/bash guest
    echo "guest:test" | chpasswd
fi

# admin: high-privilege user
if ! id admin &>/dev/null; then
    useradd -m -s /bin/bash admin
    echo "admin:complex_admin_password" | chpasswd
fi

# Give admin sudo rights
echo "admin ALL=(ALL) NOPASSWD: /usr/bin/cat, /usr/bin/find, /bin/ls" \
    > /etc/sudoers.d/admin
chmod 440 /etc/sudoers.d/admin

# ── Secret credentials (admin-only) ──────────────────────────────────────────

# Plaintext API key left in home directory
cat > /home/admin/aws_API_key.txt << 'EOF'
# API_KEY — DO NOT SHARE
# Last updated: 2025-11-03

API Key: AKIAIOSFODNN7EXAMPLE
EOF

# Only admin can read the secret
chmod 600 /home/admin/aws_API_key.txt
chown admin:admin /home/admin/aws_API_key.txt

# ── Password backup file (discoverable by guest) ─────────────────────────────
# A sysadmin "backed up" passwords in a world-readable file
mkdir -p /var/backups
cat > /var/backups/.passwd.bak << 'EOF'
# System account backup — generated by backup-users.sh
# WARNING: delete after migration
guest:guest
admin:complex_admin_password
EOF
chmod 644 /var/backups/.passwd.bak



echo "[setup] Insecure environment initialised."
